services:
  web:
    image: glitchtip/glitchtip
    env_file: .env
    volumes:
      - uploads:/code/uploads
  worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    env_file: .env
    volumes:
      - uploads:/code/uploads
  migrate:
    image: glitchtip/glitchtip
    command: ./bin/run-migrate.sh
    env_file: .env

volumes:
  uploads:
